#!/bin/sh
uci batch <<-EOF
	set luci.themes.Argon_noodles=/luci-static/argon_noodles1
	set luci.themes.Argon_colorful=/luci-static/argon_noodles2
	set luci.themes.Argon_Light_Green=/luci-static/argon_light_green
	commit luci
EOF
exit 0
